version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - unidep install .
    pre_build:
      - "jupyter-book config sphinx analysis-guide/"

conda:
  environment: .rtd-environment.yml

formats:
  - htmlzip
  - pdf

sphinx:
  builder: html
  fail_on_warning: true
