name: dkist_analysis
channels:
  - conda-forge
dependencies:
  - conda: python-graphviz  # When names differ between Conda and Pip
    pip: graphviz
  - jupyter-book
  - pip: sunpy-sphinx-theme
  - conda: graphviz!=2.42.*,!=2.43.*
  - sphinx-autobuild
